### ISSUE TITLE
Occasional 404's on some pages.

### ISSUE THREAD

**Issue by xxxoverkill** [kellenmace/wp-admin-switcher#4]
Sometimes when the extension does /wp-admin/ it will 404. To counteract, you change it to /wp/wp-admin/ . Only happens on certain websites but it does happen quite a bit.

**Comment by kellenmace** [comment]
@xxxoverkill This happens when the codebase has WordPress installed in a `/wp` subdirectory. I would try setting the `WP_SITE_URL` constant to reflect where WP lives, like this: `define('WP_SITE_URL', 'https://domain.com/wp');`. You may also need to redirect requests for `/wp-admin` to `/wp/wp-admin`. Once those are in place, this extension should work fine.

I use [Bedrock](https://roots.io/bedrock/) on a number of projects, which has WP installed inside of a `/wp` subdirectory like you're describing, and I'm able to use the cmd+shift+A shortcut to jump back to the admin without any issues.

I'm not going to make and changes to the extension at this time, since it doesn't have a way of "knowing" where the wp-admin actually lives for a given site. Depending on what the `WP_SITE_URL` constant is set to on the backend, the wp-admin could be accessible at `/wp/wp-admin`, `/wordpress/wp-admin`, `/admin-area/wp-admin`, and so on. I think the best course of action is to set that constant to point to the correct directory, then set up a redirect, if necessary, to send requests to `/wp-admin` to the proper URL, as stated above.

Hopefully that solution works well for you. Thanks for the input! 👍
